"""empty message

Revision ID: 3e4bcb3e32a6
Revises: ee017ad88917
Create Date: 2024-03-18 18:16:40.088728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4bcb3e32a6'
down_revision: Union[str, None] = 'ee017ad88917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'create_date')
    op.drop_column('study', 'owner_id')
    op.drop_column('study', 'modify_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('modify_date', sa.DATETIME(), nullable=False))
    op.add_column('study', sa.Column('owner_id', sa.INTEGER(), nullable=False))
    op.add_column('study', sa.Column('create_date', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
