"""empty message

Revision ID: 89a073603ef2
Revises: 3e4bcb3e32a6
Create Date: 2024-03-18 18:17:00.307778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a073603ef2'
down_revision: Union[str, None] = '3e4bcb3e32a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('create_date', sa.DateTime(), nullable=False))
    op.add_column('study', sa.Column('modify_date', sa.DateTime(), nullable=False))
    op.add_column('study', sa.Column('owner_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'owner_id')
    op.drop_column('study', 'modify_date')
    op.drop_column('study', 'create_date')
    # ### end Alembic commands ###
