"""empty message

Revision ID: ee017ad88917
Revises: 63606021263e
Create Date: 2024-03-17 03:19:55.963538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee017ad88917'
down_revision: Union[str, None] = '63606021263e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    # ### end Alembic commands ###
